import Head from 'next/head'
import Link from 'next/link'
import styles from '../styles/Home.module.css'
import adStyles from '../styles/Advertisers.module.css'

export default function Advertisers() {
  	return (
		<div>
			<Head>
				<title>Passive</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/icon.ico" />
			</Head>

			<main>
				<div className={styles.passive}>
					<div className={styles.tooltip}>
						<p>This is what Passive will look like, uninstrusive yet present</p>
					</div> 
					<img src="/passive.png" />
				</div>

				<div className={adStyles.header}>
					<Link href="/">
					    <h1>Passive</h1>
                    </Link>
				</div>

                <div className={adStyles.comingsoon}>
                    <p>Coming Soon... 👀</p>
                </div>

				<div className={styles.footer}>
                    <p>Contact us at passiveapp@gmail.com</p>
				</div>
				
			</main>
        </div>
	)
}
