import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Link from 'next/link'
import { initializeApp } from '@firebase/app';
import { getDatabase, ref, set } from "firebase/database";

export default function Home() {

	const firebaseApp = initializeApp({
		apiKey: 'AIzaSyBiuTVcsuig3gX8xVFOAOPso5FPKotRrFg',
		authDomain: 'passive-1642.firebaseapp.com',
		databaseURL: 'https://passive-1642-default-rtdb.firebaseio.com',
		projectId: 'passive-1642'
	});
    const db = getDatabase(firebaseApp);

	function signUp(email) {
		let filtered_email = email.split('.').join('').split('#').join('').split('$').join('').split('[').join('').split(']').join('');
		if (email != "" && email != null) {
			var date = new Date();
			set(ref(db, 'emails/' + filtered_email), {
				email: email,
				date: date.getDate() + "/" + (date.getMonth()+1) + "/" + date.getFullYear() + " @ " + date.getHours() + ":" + date.getMinutes() + ":" + date.getSeconds()
			});
			document.getElementById("signup_button").style.opacity = 0;
			document.getElementById("signup").style.opacity = 0;
			document.getElementById("signup_thanks").style.opacity = 1;
		}
	}

    function contact(email, message) {
		let filtered_email = email.split('.').join('').split('#').join('').split('$').join('').split('[').join('').split(']').join('');
		if (email != "" && email != null) {
			set(ref(db, 'contacts/' + filtered_email), {
				email: email,
				message: message
			});
			document.getElementById("send_button").innerHTML = "Thanks!";
			document.getElementById("send_button").disabled = true;
		}
	}

  	return (
		<div>
			<Head>
				<title>Passive</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/icon.ico" />
			</Head>

			<main>
				<div className={styles.passive}>
					<div className={styles.tooltip}>
						<p>This is what Passive will look like, uninstrusive yet present</p>
					</div> 
					<img src="/passive.png" />
				</div>

				<div className={styles.header}>
					<h1>Passive</h1>
					<h2>The future of mobile ads</h2>
					<hr />
					<div className={styles.signup}>
						<input type="text" placeholder="Join our mailing list to stay up to date" id="signup"></input>
						<button onClick={() => signUp(document.getElementById("signup").value)} id="signup_button">Sign Up</button>
						<p id="signup_thanks">Thank you!</p>
					</div>
					<p><i>We'll give you a $1 bonus when we launch! (promise no spam)</i></p>
				</div>

				<div className={styles.details}>
					<div>
						<h3><b>users</b></h3>
						<p>Get paid to put a small ad on your phone screen</p>
						<ul>
							<li>Download the app</li>
							<li>Sign up</li>
							<li>Set preferences</li>
							<li>Start earning!</li>
						</ul>
						<button><i>Coming Soon</i></button>
					</div>
					<div>
						<h3><b>advertisers</b></h3>
						<p>Place your ads directly on users' phone screens</p>
						<ul>
							<li>Sign up</li>
							<li>Work with us to design your ads</li>
							<li>Start advertising!</li>
						</ul>
						<Link href="/advertisers">
							<button>Get Started</button>
						</Link>
						
					</div>
				</div>

				<div className={styles.contact}>
					<p>Contact Us</p>
					<div className={styles.signup}>
						<input type="text" placeholder="Email*" id="email"></input>
						<button onClick={() => contact(document.getElementById("email").value, document.getElementById("message").value)} id="send_button">Send</button>
						<textarea placeholder="Message" id="message"></textarea>
					</div>
				</div>

				<div className={styles.footer}>
					<p>Contact us at passiveapp@gmail.com</p>
				</div>
				
			</main>
			</div>
	)
}
